### PR TITLE
Fix #6160 ui plugin detail not showing

### LINKED ISSUE #6160: Cannot view plugin info for UI plugins
**Describe the bug**

In the "Plugins > List Installed Plugins" page, clicking the "i" Info button for a UI plugin does not work.  The loading spinner appears and never resolves.  A 500 error is logged in the JS console.

**My Rundeck detail**

* Rundeck version: 3.3.0 SNAPSHOT, 3.2.x

**To Reproduce**
1. Go to 'System Config menu > Plugins >Installed Plugins'
2. Click on 'View All' type selector, choose "UI"
3. Click on the "Info" button ("i" icon) for a UI plugin
4. See loading spinner that does not resolve.

**Expected behavior**
Plugin information is displayed

**Additional context**

Stacktrace from server:

```
Caused by: java.lang.NullPointerException: Cannot get property 'value' on null object
	at rundeck.controllers.PluginController.pluginDetail(PluginController.groovy:189) ~[main/:?]
	... 79 more
```

### PR DESCRIPTION
**Pull request by gschueler**
**Is this a bugfix, or an enhancement? Please describe.**

Fix #6160

### CODE REVIEW

File: rundeckapp/grails-app/controllers/rundeck/controllers/PluginController.groovy [hunk 1]
```diff
@@ -2,6 +2,7 @@ package rundeck.controllers
 
 import com.dtolabs.rundeck.app.support.PluginResourceReq
 import com.dtolabs.rundeck.core.authorization.AuthContext
+import com.dtolabs.rundeck.plugins.rundeck.UIPlugin
```
Comment (gschueler) [inline rundeckapp/grails-app/controllers/rundeck/controllers/PluginController.groovy:5]:
```suggestion
```
