### PR TITLE
Fix error on remote opts with enforced values for simple JSON object

### LINKED ISSUE #5314: Option Validation with URLs not working
We are seeing the exact same behavior as #5030 but in a newer version of Rundeck

**My Rundeck detail**

* Rundeck version: 3.1.2.20190927
* install type: rpm
* OS Name/version: CentOS 7
* DB Type/version: postgres

**To Reproduce**
    Create a job with an option using Remote URL
    Restrict using Enforced from Allowed Values
    Required yes
    Add any step.
    Save the job.
    Run the job selecting any value from the list of options.

**Expected behavior**
The job runs successfully

**Screenshots**
See attached: Option option_name value: /mnt/share/NodalSuite/nightly_qa_deployments/QA13.json was not in the allowed values: [] 

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser Firefox
 - Version 68.0.2

**Context
We saw the same bug in 3.1.0.20190731-3 as well.

### PR DESCRIPTION
**Pull request by ProTip**
Fixes #5314 

**Is this a bugfix, or an enhancement? Please describe.**
Fix

**Describe the solution you've implemented**
`loadOptionsRemoteValues` can return three(?) different shapes for results:
- `List(Collection)<String>` for `['foo','bar']`
- `List<JSONObject>` for `[{"name": "foo", "value": "bar"}]`
- `List<LinkedHashMap>` for `{"foo":"bar"}`

Changing to `instanceof Map` will match both JSONObject and the Groovy map.

**Additional**
I believe at some point the remote option loading could afford to be refactored out into a utility class. Breaking the logic out across multiple methods and ensuring a uniform(typed?) return schema regardless of the supported input JSON shape could help with test-ability and maintainability.

### CODE REVIEW

File: rundeckapp/src/test/groovy/ExecutionServiceSpec.groovy [hunk 1]
```diff
@@ -1498,28 +1498,31 @@ class ExecutionServiceSpec extends Specification implements ServiceUnitTest<Exec
...
                     srcUrl       : "cleanUrl",
                     err          : null
             ]
         }
 
 
         ExecutionServiceValidationException e = thrown()
+        e.errors.each { k, v ->
+            println("${k} ${v}")
+        }
```
Comment (sjrd218) [inline rundeckapp/src/test/groovy/ExecutionServiceSpec.groovy]: No need to keep the println.

File: rundeckapp/src/integration-test/groovy/rundeck/services/ExecutionServiceIntegrationSpec.groovy [hunk 2]
```diff
@@ -0,0 +1,4 @@
+package rundeck.services
```
Comment (sjrd218) [inline rundeckapp/src/integration-test/groovy/rundeck/services/ExecutionServiceIntegrationSpec.groovy]: This file seems unnecessary. Can we remove it?

Comment (ProTip) [reply rundeckapp/src/integration-test/groovy/rundeck/services/ExecutionServiceIntegrationSpec.groovy]: Hah, yes.. That was abandoned. It seemed like a good idea and turned into a massive PITA.

**Comment by menicolas89** [comment]
any luck with this review. thanks!

**Comment by sjrd218** [comment]
@ProTip Looks like you might have to rebase this to get it to build.
