### PR TITLE
RUN-794: Putting back config attribute useForwardHeaders to avoid https redirecting back to HTTP

### LINKED ISSUE #7605: Rundeck v4.0.0-20220322 started redirecting back to HTTP
**Problem**
After upgrading to `v4.0.0-20220322`, Rundeck wants to redirect users back to HTTP instead of HTTPS. I ended up downgrading our rundeck to `Community 3.4.10`

**My Rundeck detail**
Our current Rundeck environment is hosted in GCP, and is using GCP Load Balancer:
`External GCP Load Balancer (HTTPS using 443) > Rundeck instance (4440)`
Ever since we have upgraded to the latest 4.0.0 version, it started redirecting users to HTTP `/user/login` page.

* Environment: Rundeck instance, load balancer, and MySQL are in GCP Cloud
* Rundeck version: `v4.0.0-20220322`
* Install type: Installed through rundeck repo: `https://packages.rundeck.com/pagerduty/rundeck/rpm_any/rpm_any/$basearch`
* OS Name/version: `CentOS Linux release 7.9.2009 (Core)`
* DB Type/version: `MySQL 5.7`
* We are handing off SSL to the load balancer and the load balancer's backend is connecting to the port4440 of the instance

**To Reproduce**
1. Ran `sudo yum update rundeck` to update to the latest version, `v4.0.0-20220322`
2. Restarted `rundeckd` service
3. Tried any browser, and head over to `https://rundeck.contoso.com/`
4. Returns back and attempts redirect to `http://rundeck.contoso.com/user/login`

**Expected behavior**
When the user head over to `https://rundeck.contoso.com/`, it should redirect the page to `/user/login` with HTTPS URL, `https://rundeck.contoso.com/user/login`. However, it is redirecting back to HTTP, `http://rundeck.contoso.com/user/login` instead.

Below is a curl request. I have a masked URL, but you get the point.
```
$ curl -I https://rundeck.contoso.com/
HTTP/2 302
date: Wed, 23 Mar 2022 15:58:21 GMT
vary: Origin
vary: Access-Control-Request-Method
vary: Access-Control-Request-Headers
set-cookie: JSESSIONID=node0rdl7ten0seb11kkver3j8l9j320.node0; Path=/; HttpOnly
expires: Thu, 01 Jan 1970 00:00:00 GMT
location: http://rundeck.contoso.com/user/login
content-length: 0
via: 1.1 google
alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
```

**Desktop (please complete the following information):**
Any browsers

**Additional context**
Here are some of the snippet of the rundeck configuration:

**/etc/rundeck/rundeck-config.properties**
```
#loglevel.default is the default log level for jobs: ERROR,WARN,INFO,VERBOSE,DEBUG
loglevel.default=INFO
rdeck.base=/var/lib/rundeck

#rss.enabled if set to true enables RSS feeds that are public (non-authenticated)
rss.enabled=false
# change hostname here
grails.serverURL=https://rundeck.contoso.com

```

**/etc/rundeck/profile**
```
RDECK_INSTALL="${RDECK_INSTALL:-/var/lib/rundeck}"
RDECK_BASE="${RDECK_BASE:-/var/lib/rundeck}"
RDECK_CONFIG="${RDECK_CONFIG:-/etc/rundeck}"
RDECK_CONFIG_FILE="${RDECK_CONFIG_FILE:-$RDECK_CONFIG/rundeck-config.properties}"
RDECK_SERVER_BASE="${RDECK_SERVER_BASE:-$RDECK_BASE}"
RDECK_SERVER_CONFIG="${RDECK_SERVER_CONFIG:-$RDECK_CONFIG}"
RDECK_SERVER_DATA="${RDECK_SERVER_DATA:-$RDECK_BASE/data}"
RDECK_PROJECTS="${RDECK_PROJECTS:-$RDECK_BASE/projects}"
RUNDECK_TEMPDIR="${RUNDECK_TEMPDIR:-/tmp/rundeck}"
RUNDECK_WORKDIR="${RUNDECK_TEMPDIR:-$RDECK_BASE/work}"
RUNDECK_LOGDIR="${RUNDECK_LOGDIR:-$RDECK_BASE/logs}"
RDECK_JVM_SETTINGS="${RDECK_JVM_SETTINGS:- -Xmx1024m -Xms256m -XX:MaxMetaspaceSize=256m -server}"
RDECK_TRUSTSTORE_FILE="${RDECK_TRUSTSTORE_FILE:-$RDECK_CONFIG/ssl/truststore}"
RDECK_TRUSTSTORE_TYPE="${RDECK_TRUSTSTORE_TYPE:-jks}"
JAAS_LOGIN="${JAAS_LOGIN:-true}"
JAAS_CONF="${JAAS_CONF:-$RDECK_CONFIG/jaas-loginmodule.conf}"
LOGIN_MODULE="${LOGIN_MODULE:-RDpropertyfilelogin}"
RDECK_HTTP_PORT=${RDECK_HTTP_PORT:-4440}
RDECK_HTTPS_PORT=${RDECK_HTTPS_PORT:-4443}

RDECK_JVM="-Drundeck.jaaslogin=$JAAS_LOGIN \
           -Djava.security.auth.login.config=$JAAS_CONF \
           -Dloginmodule.name=$LOGIN_MODULE \
           -Drdeck.config=$RDECK_CONFIG \
           -Drundeck.server.configDir=$RDECK_SERVER_CONFIG \
           -Dserver.datastore.path=$RDECK_SERVER_DATA/rundeck \
           -Drundeck.server.serverDir=$RDECK_INSTALL \
           -Drdeck.projects=$RDECK_PROJECTS \
           -Drdeck.runlogs=$RUNDECK_LOGDIR \
           -Drundeck.config.location=$RDECK_CONFIG_FILE \
           -Djava.io.tmpdir=$RUNDECK_TEMPDIR \
           -Drundeck.server.workDir=$RUNDECK_WORKDIR \
           -Dserver.http.port=$RDECK_HTTP_PORT \
           -Drdeck.base=$RDECK_BASE \
           -Dlog4j2.formatMsgNoLookups=true \
           -Dlog4j.formatMsgNoLookups=true \
           -Drundeck.jetty.connector.forwarded=true"
```

### PR DESCRIPTION
**Pull request by carlosrfranco**
fixes #7605

**Is this a bugfix, or an enhancement? Please describe.**
This PR fixes redirecting to http if config property `server.useForwardHeaders` or sys config `rundeck.jetty.connector.forwarded` is true

**Describe the solution you've implemented**
The useForwardHeaders attribute on JettyServletWebServerFactory was not being configured as apparently part of the code had been removed

**Describe alternatives you've considered**
Looks like this code was removed a long time ago so I was trying to figure out why it seems to be working in 3.4.x versions

### CODE REVIEW

File: rundeckapp/grails-app/conf/spring/resources.groovy [hunk 1]
```diff
@@ -757,6 +757,8 @@ beans={
         initParams = configParams?.toProperties()?.collectEntries {
             [it.key.toString(), it.value.toString()]
         }
+
+        useForwardHeaders = Boolean.getBoolean('rundeck.jetty.connector.forwarded')
```
Comment (gschueler) [inline rundeckapp/grails-app/conf/spring/resources.groovy:761]: this is only reading the java system property, this should support the app config

**Comment by fdevans** [comment]
Due to the number of issues this bug is causing we are going to move this up to `4.1.0` release.

File: rundeckapp/grails-app/conf/spring/resources.groovy [hunk 2]
```diff
@@ -753,10 +753,13 @@ beans={
 
     jettyServletCustomizer(JettyServletContainerCustomizer) {
         def configParams = grailsApplication.config.getProperty("rundeck.web.jetty.servlet.initParams", String.class)
+        def useForwardHeadersConfig = grailsApplication.config.getProperty("server.useForwardHeaders")
```
Comment (gschueler) [inline rundeckapp/grails-app/conf/spring/resources.groovy:756]: why not do `getProperty("server.useForwardHeaders",Boolean.class)`

**Review by ltamaster — APPROVED** [review]
it worked for me

**Comment by ledufakademy** [comment]
And for endusers, what is the fix ?

**Comment by ledufakademy** [comment]
when did you plan to release the fix ?

**Comment by gschueler** [comment]
@ledufakademy this should be in 4.1.0 which is already released

**Comment by AMKamel** [comment]
I have tried to resolve this on my docker instance behind Nginx as reverse proxy and ssl off loader on version 4.0.1 and 4.2 now and nothing works at my side at all and the only solution that worked with me is to proxy redirect http to https traffic by adding the following directive inside nginx configuration block
```
proxy_redirect http://example.com https://example.com;
```
like this
```
     location / {
         proxy_pass http://127.0.0.1:14081;
         proxy_http_version  1.1;
         proxy_cache_bypass  $http_upgrade;
         proxy_set_header Upgrade            $http_upgrade;
         proxy_set_header Connection         "upgrade";
         proxy_set_header Host               $host;
         proxy_set_header X-Real-IP          $remote_addr;
         proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
         proxy_set_header X-Forwarded-Proto  $scheme;
         proxy_set_header X-Forwarded-Host   $host;
         proxy_set_header X-Forwarded-Port   $server_port;
         proxy_redirect http://example.com https://example.com;
     }

```
