### PR TITLE
Fix execution log viewer not updating settings on running job

### LINKED ISSUE #1334: Rundeck upgrade to 2.5.1 failed due to java.lang.ClassNotFoundException: org.codehaus.groovy.grails.web.sitemesh.GrailsPageFilter
I upgraded from 2.3 to 2.5.1, first it worked with one user role problem, After I updated the web.xml file and restarted the rundeckd service I got 
HTTP ERROR: 503

Problem accessing /rundeck. Reason:

    Service Unavailable

My service.log file shows:

java.lang.ClassNotFoundException: org.codehaus.groovy.grails.web.sitemesh.GrailsPageFilter
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:424)
	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:377)
	at org.eclipse.jetty.util.Loader.loadClass(Loader.java:92)
	at org.eclipse.jetty.util.Loader.loadClass(Loader.java:71)
	at org.eclipse.jetty.servlet.Holder.doStart(Holder.java:84)
	at org.eclipse.jetty.servlet.FilterHolder.doStart(FilterHolder.java:74)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:747)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:249)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1214)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:676)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:455)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:90)
	at org.eclipse.jetty.server.Server.doStart(Server.java:261)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at com.dtolabs.rundeck.RunServer.run(RunServer.java:118)
	at com.dtolabs.rundeck.RunServer.main(RunServer.java:78)
2015-07-15 16:17:04.243:WARN:oejuc.AbstractLifeCycle:FAILED sitemesh: javax.servlet.UnavailableException: org.codehaus.groovy.grails.web.sitemesh.GrailsPageFilter
javax.servlet.UnavailableException: org.codehaus.groovy.grails.web.sitemesh.GrailsPageFilter
	at org.eclipse.jetty.servlet.Holder.doStart(Holder.java:91)
	at org.eclipse.jetty.servlet.FilterHolder.doStart(FilterHolder.java:74)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:747)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:249)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1214)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:676)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:455)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:90)
	at org.eclipse.jetty.server.Server.doStart(Server.java:261)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at com.dtolabs.rundeck.RunServer.run(RunServer.java:118)
	at com.dtolabs.rundeck.RunServer.main(RunServer.java:78)
2015-07-15 16:17:04.244:WARN:oejw.WebAppContext:Failed startup of context o.e.j.w.WebAppContext{/rundeck,file:/var/lib/rundeck/exp/webapp/},/var/lib/rundeck/exp/webapp
javax.servlet.UnavailableException: org.codehaus.groovy.grails.web.sitemesh.GrailsPageFilter
	at org.eclipse.jetty.servlet.Holder.doStart(Holder.java:91)
	at org.eclipse.jetty.servlet.FilterHolder.doStart(FilterHolder.java:74)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:747)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:249)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1214)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:676)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:455)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:90)
	at org.eclipse.jetty.server.Server.doStart(Server.java:261)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at com.dtolabs.rundeck.RunServer.run(RunServer.java:118)
	at com.dtolabs.rundeck.RunServer.main(RunServer.java:78)
2015-07-15 16:17:04.267:INFO:oejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0:4440

Please help
Thanks

### PR DESCRIPTION
**Pull request by imad6639**
Fixes rundeckpro/rundeckpro#1334

While running a job some settings from the new execution viewer does not keep saved as being enabled/disabled during the job execution.

I.e, during job execution > select settings > uncheck Display Gutter > Gutter disappears > when output is updated it reverts back to how it was configured since job started.

Fixed by assigning the current settings props in the store to the new entries before they are pushed to the log builder

### CODE REVIEW

File: rundeckapp/grails-spa/packages/ui-trellis/src/components/execution-log/logViewer.vue [hunk 1]
```diff
@@ -478,9 +478,14 @@ export default class LogViewer extends Vue {
     }
 
     private handleNewLine(entries: Array<any>) {
+       const updatableProps: Array<keyof IEventViewerSettings> = ['nodeBadge', 'gutter', 'timestamps', 'lineWrap', 'command']
 
       for (const vue of entries) {
         // @ts-ignore
+          for (const prop of updatableProps) {
```
Comment (ProTip) [inline rundeckapp/grails-spa/packages/ui-trellis/src/components/execution-log/logViewer.vue:485]: What do you think about updating the log builder with the new options in `@Watch('settingsChange'` so it builds the entries with the current settings?

File: rundeckapp/grails-spa/packages/ui-trellis/src/components/execution-log/logViewer.vue [hunk 2]
```diff
@@ -478,9 +478,14 @@ export default class LogViewer extends Vue {
     }
 
     private handleNewLine(entries: Array<any>) {
+       const updatableProps: Array<keyof IEventViewerSettings> = ['nodeBadge', 'gutter', 'timestamps', 'lineWrap', 'command']
```
Comment (ProTip) [inline rundeckapp/grails-spa/packages/ui-trellis/src/components/execution-log/logViewer.vue:481]: Is this a dupe of the set in `@Watch('settingsChange'`?

File: rundeckapp/grails-spa/packages/ui-trellis/src/components/execution-log/logViewer.vue (hunk 1 above)
Comment (imad6639) [reply rundeckapp/grails-spa/packages/ui-trellis/src/components/execution-log/logViewer.vue]: Good catch, Changed this approach.

File: rundeckapp/grails-spa/packages/ui-trellis/src/components/execution-log/logViewer.vue (hunk 2 above)
Comment (imad6639) [reply rundeckapp/grails-spa/packages/ui-trellis/src/components/execution-log/logViewer.vue]: Removed

**Review by ProTip — APPROVED** [review]
Awesome, tested in storybook with the running output and works great!
