### PR TITLE
Stop holding DB connections during job execution

### LINKED ISSUE #4459: Rundeck holds connections on job referenced jobs
**Describe the bug**
Rundeck is holding the connections to backend DB when there are references to other jobs.
These connections will be held as long as the child job is still running and it can be several hours. If there are many such jobs, we will end up in a situation where Rundeck is holding many idle connections for a lot of time with backend DB

**My Rundeck detail**

* Rundeck version: 3.0.9
* install type: rpm
* OS Name/version: ubuntu 18.04
* DB Type/version: Mysql: version: 5.6.22-72

**To Reproduce**
running job referenced jobs

### PR DESCRIPTION
**Pull request by ProTip**
Fixes #4459 

This builds off the work @jtobard completed in #4641.

During testing against MySQL with low `wait_timeout` I was still getting errors about the underlying connection being dead after the job finishes. This was strange as I could not see a running transaction in `show engine innodb status`.

### Test Setup
**MySQL**
```
SET GLOBAL wait_timeout=15
```
**Rundeck**
```
dataSource.properties.validationInterval=5000
dataSource.properties.testOnBorrow=true
dataSource.properties.testWhileIdle=true
dataSource.properties.testOnReturn=true
dataSource.properties.timeBetweenEvictionRunsMillis=5000
```

### Test Results
Running `show full processlist` would display something like the following:
```
mysql> show full processlist;
+-----+---------+------------------+---------+---------+------+----------+-----------------------+
| Id  | User    | Host             | db      | Command | Time | State    | Info                  |
+-----+---------+------------------+---------+---------+------+----------+-----------------------+
|   2 | root    | localhost        | rundeck | Query   |    0 | starting | show full processlist |
| 203 | rundeck | 172.22.0.1:56492 | rundeck | Sleep   |    2 |          | NULL                  |
| 204 | rundeck | 172.22.0.1:45448 | rundeck | Sleep   |    2 |          | NULL                  |
| 205 | rundeck | 172.22.0.1:48274 | rundeck | Sleep   |    2 |          | NULL                  |
| 206 | rundeck | 172.22.0.1:51028 | rundeck | Sleep   |    2 |          | NULL                  |
| 207 | rundeck | 172.22.0.1:53740 | rundeck | Sleep   |    2 |          | NULL                  |
| 208 | rundeck | 172.22.0.1:56334 | rundeck | Sleep   |    2 |          | NULL                  |
| 209 | rundeck | 172.22.0.1:58902 | rundeck | Sleep   |    2 |          | NULL                  |
| 210 | rundeck | 172.22.0.1:33372 | rundeck | Sleep   |    2 |          | NULL                  |
| 211 | rundeck | 172.22.0.1:36322 | rundeck | Sleep   |    2 |          | NULL                  |
| 212 | rundeck | 172.22.0.1:38970 | rundeck | Sleep   |    0 |          | NULL                  |
+-----+---------+------------------+---------+---------+------+----------+-----------------------+
```
The sleep command time would go up to 5 or at most 10, then it would reset as the tomcat JDBC pool runs the validation query. This indicates all open connections are in the pool.

Running a 20 second sleep job ref I could see one connection would go past 10 seconds and right up until the job finishes. This indicated that the connection was checked out of the pool even though there was no command running on it.

### Root Cause
It turns out that the `ExecutionService` class is marked `@Transactional` causing every method to be implicitly wrapped in a transaction and thus Hibernate session. This includes `executeWorkflowStep` which is the entry-point from the `ExecutionServiceImpl`.  Because of this implicit transaction, a hibernate session was being kept open in the background while the step was executed.

### Solution
Logically `runJobRefExecutionItem` is multiple units of work that were all being wrapped up as one:
* [T]Validation and book keeping
* Execute the workflow
* [T]Validation and book keeping

By adding `@Transactional(propagation = Propagation.NOT_SUPPORTED)` to `executeWorkflowStep` we opt out of the implicit transaction. From there sessions are manually opened via `withTransaction`, variables definitions used in the closures hoisted, and some general teasing apart allows for the execution to proceed without holding a database connection open.

### CODE REVIEW

File: rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy [hunk 1]
```diff
@@ -3473,34 +3485,28 @@ class ExecutionService implements ApplicationContextAware, StepExecutor, NodeSte
...
             }
-
-            throw new StepException(msg, JobReferenceFailureReason.NoMatchedNodes)
         }
 
         long startTime = System.currentTimeMillis()
 
-        def wresult = metricService.withTimer(this.class.name,'runJobReference') {
+        def wresult = metricService.withTimer(this.class.name, 'runJobReference') {
+            println("Made it!!!!")
```
Comment (sjrd218) [inline rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy]: Let's kill the println.
