### PR TITLE
Fixes webhook notification issue that use credentials in URL

### LINKED ISSUE #6690: notification "send webhook": user:password@url format not working
**Describe the bug**
When setting a "send webhook" notification using format user:password@url, it is not working.

**My Rundeck detail**

* Rundeck version: 3.3.7
* install type: war
* OS Name/version: linuxmint 20.04
* DB Type/version: mysql, h2

**To Reproduce**
1. Go to job's notification job
2. Add url in user:password@url format (webhook to jenkins for example)
3. Run it
4. See error in service.log
    [2020-12-22T13:04:38,081] ERROR services.NotificationService - Notification failed [onsuccess,succeeded,5]; URL http://user:TOKEN@url/job/triggered.build.from.rundeck/build?token=TOKEN: Unable to POST notification after 1 tries: success for execution 5 (succeeded): server response: 403 Forbidden

**Expected behavior**
Same format is working fine using "http notification" notification and from command line (curl)

### PR DESCRIPTION
**Pull request by carlosrfranco**
Fixes #6690 

**Is this a bugfix, or an enhancement? Please describe.**
Webhook notification is not working if use credentials on URL like `user:password@url`

**Describe the solution you've implemented**
When trying to reproduce the issue, I realized that Jenkins returns this error if it uses POST and not GET to trigger a job remotely. These changes are a suggestion to be able to use the webhook notification to make a GET request.

### CODE REVIEW

File: rundeckapp/src/test/groovy/rundeck/services/NotificationServiceSpec.groovy [hunk 1]
```diff
@@ -811,11 +811,76 @@ class NotificationServiceSpec extends HibernateSpec implements ServiceUnitTest<N
...
+
+        when:
+        def result = NotificationService.postDataUrl(endpoint,format,payload,"success","suceeded","1234")
+        RecordedRequest rq = httpServer.takeRequest()
+
+        then:
+        result.success
+        (rq.getHeader("X-RunDeck-Notification-SHA256-Digest") != null) == generatedDigestExists
+        rq.getHeader("Content-Type") == expectedContentType
+        rq.body.readUtf8() == payload
```
Comment (gschueler) [inline rundeckapp/src/test/groovy/rundeck/services/NotificationServiceSpec.groovy:839]: should test request headers for basic auth are present

File: rundeckapp/src/test/groovy/rundeck/services/NotificationServiceSpec.groovy [hunk 2]
```diff
@@ -811,11 +811,76 @@ class NotificationServiceSpec extends HibernateSpec implements ServiceUnitTest<N
...
+        String endpoint = httpServer.url("hook/endpoint").toString()
+        String format = "json"
+        String payload = '{"job":"1234"}'
+
+        when:
+        def result = NotificationService.postDataUrl(endpoint,format,payload,"success","suceeded","1234", NotificationService.GET)
+        RecordedRequest rq = httpServer.takeRequest()
+
+        then:
+        result.success
```
Comment (gschueler) [inline rundeckapp/src/test/groovy/rundeck/services/NotificationServiceSpec.groovy:864]: should verify request method

File: rundeckapp/src/test/groovy/rundeck/services/NotificationServiceSpec.groovy [hunk 3]
```diff
@@ -811,11 +811,76 @@ class NotificationServiceSpec extends HibernateSpec implements ServiceUnitTest<N
...
+        endpoint = endpoint.replaceAll('localhost', 'user:pswd@localhost')
+        String format = "json"
+        String payload = '{"job":"1234"}'
+
+        when:
+        def result = NotificationService.postDataUrl(endpoint,format,payload,"success","suceeded","1234", NotificationService.GET)
+        RecordedRequest rq = httpServer.takeRequest()
+
+        then:
+        result.success
```
Comment (gschueler) [inline rundeckapp/src/test/groovy/rundeck/services/NotificationServiceSpec.groovy:883]: should verify request method, and auth headers

File: rundeckapp/src/test/groovy/rundeck/NotificationSpec.groovy [hunk 4]
```diff
@@ -69,12 +69,8 @@ class NotificationSpec extends Specification {
...
         where:
             data                                                                      | expected
-            [eventTrigger: 'onsuccess', type: 'url', content: 'asdf', format: 'xml']  | [type: 'url', trigger:
-                'onsuccess', config                                                          : [urls: 'asdf', format:
-                'xml']]
-            [eventTrigger: 'onsuccess', type: 'url', content: 'asdf', format: 'json'] | [type: 'url', trigger:
-                'onsuccess', config                                                          : [urls: 'asdf', format:
-                'json']]
+            [eventTrigger: 'onsuccess', type: 'url', content: 'asdf', format: 'xml']  | [type:'url', trigger:'onsuccess', config:[urls:'asdf', format:'xml', httpMethod:null]]
+            [eventTrigger: 'onsuccess', type: 'url', content: 'asdf', format: 'json'] | [type:'url', trigger:'onsuccess', config:[urls:'asdf', format:'json', httpMethod:null]]
```
Comment (gschueler) [inline rundeckapp/src/test/groovy/rundeck/NotificationSpec.groovy:73]: need tests for added behavior to Notification.groovy

**Review by gschueler — CHANGES_REQUESTED** [review]

**Review by gschueler — APPROVED** [review]
