### PR TITLE
Fix #5943 - Avoiding creating temporary files when deleting executions

### LINKED ISSUE #5943: Job Execution Cleanup process creates many tmp files
**Describe the bug**
50,000 plus files at /tmp/rundeck
with about 5000 executions per day I'm currently seeing about 50k execution-....xml files under /tmp/rundeck

would like to understand what's going on there, how often are those cleaned up, is this normal expected behavior etc.

**My Rundeck detail**

* Rundeck version: Rundeck 3.2.3-20200221
* install type: RPM
* OS Name/version: CentOS 7
* DB Type/version: postgres

**To Reproduce**
run jobs

**Expected behavior**
an understanding of what's going on in /tmp related to Rundeck

### PR DESCRIPTION
**Pull request by carlosrfranco**
Fix #5943 

**Is this a bugfix, or an enhancement? Please describe.**
Temporary files are being created when deleting executions. This becomes an issue especially when the "Executions History Cleaner" feature is enabled and removes many files frequently.

**Describe the solution you've implemented**
The file path for the xml file created when execution finish should be determined from logFileStorageService.getFileForExecutionFiletype

**Additional context**
The creation of the file at the end of the execution was also updated to obtain the file path in the same way instead of being constructed

### CODE REVIEW

**Comment by MegaDrive68k** [comment]
Fix tested and works OK.

3.2.5:

Screenshot_1

SNAPSHOT:

Screenshot_2

File: rundeckapp/grails-app/services/rundeck/services/ExecutionUtilService.groovy [hunk 1]
```diff
@@ -336,12 +339,10 @@ class ExecutionUtilService {
      * @param path path to store the file on filesystem. If null a temporary file will be created and deleted.
      * @return file containing execution.xml
      */
-    File getExecutionXmlFileForExecution(Execution execution, String path = null) {
-        File executionXmlfile
-        if(path){
-            executionXmlfile  = new File(path, "${execution.id}.execution.xml")
-        }else{
+    File getExecutionXmlFileForExecution(Execution execution, File executionXmlfile = null) {
```
Comment (gschueler) [inline rundeckapp/grails-app/services/rundeck/services/ExecutionUtilService.groovy:342]: getExecutionXmlFileForExecution is not used anywhere except here https://github.com/rundeck/rundeck/pull/5966/files#diff-d5afe3953d1f462e7d2662435b77507eR81

so i would remove the temp file creation altogether

Comment (carlosrfranco) [reply rundeckapp/grails-app/services/rundeck/services/ExecutionUtilService.groovy]: done

**Comment by jimr6007** [comment]
Valeu, Carlos !
