### PR TITLE
Change http return when execution status is passive from 503 to 200

### LINKED ISSUE #5846: GET /api/32/system/executions/status should not return 503 when the execution mode is set to passive
**Describe the bug**
GET /api/32/system/executions/status currently returns HTTP status 503 when the execution mode is set to passive.  Although this is documented here: https://docs.rundeck.com/docs/api/rundeck-api.html#get-current-execution-mode , that is not a good reason to permit this to continue - functioning APIs should never return 500 codes.

**Expected behavior**
The expected behavior is for the endpoint to return a response symmetric with the response sent when the status is active.

**Additional context**
APIs should never return 500 codes.

### PR DESCRIPTION
**Pull request by sjrd218**
Fixes #5846

### CODE REVIEW

File: rundeckapp/grails-app/controllers/rundeck/controllers/ExecutionController.groovy [hunk 1]
```diff
@@ -2290,15 +2290,19 @@ setTimeout(function(){
 
         def executionStatus = configurationService.executionModeActive
         int respStatus = executionStatus ? HttpServletResponse.SC_OK : HttpServletResponse.SC_SERVICE_UNAVAILABLE
+        boolean apiVersionAfterV35 = request.api_version > ApiVersions.V35
+        if(apiVersionAfterV35 && !executionStatus) {
+            respStatus =  params.passiveAs503 ? HttpServletResponse.SC_SERVICE_UNAVAILABLE : HttpServletResponse.SC_OK
```
Comment (gschueler) [inline rundeckapp/grails-app/controllers/rundeck/controllers/ExecutionController.groovy:2295]:
```suggestion
            respStatus =  params.boolean('passiveAs503',false) ? HttpServletResponse.SC_SERVICE_UNAVAILABLE : HttpServletResponse.SC_OK
```

problem: `params.passiveAs503` will resolve to true if any value is present (groovy truth)

File: rundeckapp/src/test/groovy/rundeck/controllers/ExecutionControllerTests.groovy [hunk 2]
```diff
@@ -876,8 +877,14 @@ class ExecutionControllerTests extends HibernateSpec implements ControllerUnitTe
 
         then:
         // Check respose.
-        assert 503 == controller.response.status
+        assert expectedStatus == controller.response.status
         assert resp.executionMode == "passive"
+
+        where:
+        apiVersion | passiveAs503 | expectedStatus
+        35         | false        | 503             //ignore passive parameter before V36
```
Comment (gschueler) [inline rundeckapp/src/test/groovy/rundeck/controllers/ExecutionControllerTests.groovy:885]:
```suggestion
        35         | 'false'        | 503             //ignore passive parameter before V36
```

File: rundeckapp/src/test/groovy/rundeck/controllers/ExecutionControllerTests.groovy [hunk 3]
```diff
@@ -876,8 +877,14 @@ class ExecutionControllerTests extends HibernateSpec implements ControllerUnitTe
...
+        36         | false        | 200
```
Comment (gschueler) [inline rundeckapp/src/test/groovy/rundeck/controllers/ExecutionControllerTests.groovy:886]:
```suggestion
        36         | 'false'        | 200
```

File: rundeckapp/src/test/groovy/rundeck/controllers/ExecutionControllerTests.groovy [hunk 4]
```diff
@@ -876,8 +877,14 @@ class ExecutionControllerTests extends HibernateSpec implements ControllerUnitTe
...
+        36         | true         | 503
```
Comment (gschueler) [inline rundeckapp/src/test/groovy/rundeck/controllers/ExecutionControllerTests.groovy:887]:
```suggestion
        36         | 'true'         | 503
```
