### PR TITLE
Project description on project list api call

### LINKED ISSUE #3827: API 25 list of projects : desciption empty and label missing
**Describe the bug**
Hello,

There is no longer in the list of projects via the API the description of the projects.
Moreover it would be possible to have in addition to the name, the label of the project.

**My Rundeck detail**

* Rundeck version: 3.1
* install type: rpm
* OS Name/version: Centos 7.3
* DB Type/version: postgres

**To Reproduce**
https://rundeck.mydomaine.fr/api/25/projects

API 25:
rundeck-api25

GUI:
rundeck-gui

### PR DESCRIPTION
**Pull request by jtobard**
fix #3827 

Project description from project configuration file and adds the label on new API version v26

Using API version >=26 adds the project `label` to the API call  `/api/26/projects` 

```
[
    {
        "name":"...",
        "description":"...",
        "url":"...",
       "label":"..."
    }
]
```
Doc documentation PR: rundeck/docs#72

### CODE REVIEW

File: rundeckapp/src/test/groovy/rundeck/controllers/ApiControllerSpec.groovy [hunk 1]
```diff
@@ -239,15 +239,15 @@ class ApiControllerSpec extends Specification {
...
+        ''    | [ping: true]                                                  | true                                                                             | false                                                                                                | [ping: [href: '/api/26/metrics/ping']]
+        ''    | [threads: true]                                               | true                                                                          | false                                                                                                | [threads: [href: '/api/26/metrics/threads']]
         ''    | [threads: true, ping: true, metrics: true, healthcheck: true] | true                            | false                                                                                                | [
-            metrics    : [href: '/api/25/metrics/metrics'],
-            threads    : [href: '/api/25/metrics/threads'],
-            healthcheck: [href: '/api/25/metrics/healthcheck'],
-            ping       : [href: '/api/25/metrics/ping'],
+            metrics    : [href: '/api/26/metrics/metrics'],
```
Comment (gschueler) [inline rundeckapp/src/test/groovy/rundeck/controllers/ApiControllerSpec.groovy]: this should probably change to `href: "/api/${ApiVersions.API_CURRENT_VERSION}/metrics/metrics"` so it doesn't have to change with each new version
